/**
 * Top-down Zelda-style maps for Arcanum.
 * Legend: . floor  # wall  D door  S seal  C chest  N npc marker (see entities)
 * ~ grass  = path  ^ torch
 */
window.EXPLORE_MAPS = {
  courtyard: {
    id: "courtyard",
    name: "Castle Courtyard",
    musicCue: "map",
    tile: 40,
    spawn: { x: 12, y: 16 },
    // width 24, height 18
    rows: [
      "########################",
      "#~~..............~~~~##",
      "#~~..^^^^........~~~~##",
      "#....................##",
      "#..####......####....##",
      "#..#N.#......#..#....##",
      "#..#..D......D..#....##",
      "#..####......####....##",
      "#....................##",
      "#........CC..........##",
      "#....................##",
      "#~~..............~~~~##",
      "#~~.....=..=.....~~~~##",
      "#.......====.........D#",
      "#.......=..=.........D#",
      "#....................##",
      "#..........@.........##",
      "########################",
    ],
    entities: [
      {
        id: "npc-elowen",
        type: "npc",
        charId: "elowen",
        x: 4.5,
        y: 5.5,
        color: "#3d7a4f",
        wander: true,
        lines: [
          "Walk the courtyard. Seals wait inside the west wing when you are ready.",
          "True mastery is not a quiz — it is how you move through the castle.",
          "Find lore scraps. Speak to souls. Then challenge the Protease Seal.",
        ],
        bond: "elowen",
        xp: 8,
      },
      {
        id: "npc-cassian",
        type: "npc",
        charId: "cassian",
        x: 15.5,
        y: 5.5,
        color: "#8a3420",
        wander: true,
        lines: [
          "Still gawking at the sky? East door is Mercury — locked until you prove Asphodel.",
          "I left a wager chest near the fountain. Try not to embarrass yourself.",
        ],
        bond: "cassian",
        xp: 6,
      },
      {
        id: "npc-bramble",
        type: "npc",
        charId: "bramble",
        x: 10,
        y: 9.5,
        color: "#c4a35a",
        wander: true,
        lines: [
          "Bramble swept the stones thrice! Chests hide charms. Charms help later casts.",
          "Touch a glowing seal only when your feet are ready — not before.",
        ],
        bond: "bramble",
        xp: 7,
      },
      {
        id: "npc-lyra",
        type: "npc",
        charId: "lyra",
        x: 18,
        y: 11,
        color: "#7aa0b8",
        wander: false,
        lines: [
          "I remember every footstep that hesitated. Explore. The stones teach before the wards.",
          "A lore page drifts by the south wall. Take it — memory loves images.",
        ],
        bond: "lyra",
        xp: 8,
      },
      {
        id: "door-asphodel",
        type: "door",
        x: 5,
        y: 6,
        label: "Wing of Asphodel",
        targetMap: "asphodel",
        targetSpawn: { x: 2, y: 8 },
      },
      {
        id: "door-mercury",
        type: "door",
        x: 14,
        y: 6,
        label: "Wing of Mercury",
        targetMap: "mercury",
        targetSpawn: { x: 2, y: 7 },
        requiresWorld: "wing-mercury",
        lockedText: "Sealed. Clear Asphodel's main seals first.",
      },
      {
        id: "door-path-east",
        type: "door",
        x: 22,
        y: 13.5,
        label: "East colonnade",
        targetMap: "asphodel",
        targetSpawn: { x: 18, y: 8 },
      },
      {
        id: "chest-rival",
        type: "chest",
        x: 10,
        y: 9,
        loot: "rival_charm",
        xp: 15,
        text: "Cassian's wager chest. Inside: a Rival Charm — bonds with Cassian deepen.",
      },
      {
        id: "chest-herb",
        type: "chest",
        x: 11,
        y: 9,
        loot: "herb_sachet",
        xp: 12,
        text: "A herb sachet. Bramble will approve — and your Grimoire notes a calm mood.",
      },
      {
        id: "lore-courtyard",
        type: "lore",
        x: 19,
        y: 15,
        loreId: "courtyard-1",
        xp: 10,
        title: "Courtyard Glyph",
        text: "Memory mark: walk before you cast. Exploration XP levels your scholar outside any ward.",
      },
    ],
  },

  asphodel: {
    id: "asphodel",
    name: "Wing of Asphodel",
    musicCue: "wing-asphodel",
    tile: 40,
    spawn: { x: 2, y: 8 },
    rows: [
      "####################",
      "#..................#",
      "#..####....####....#",
      "#..#S.#....#..#....#",
      "#..#..#....#N.#....#",
      "#..####....####....#",
      "#..................#",
      "#D........C........#",
      "#..................#",
      "#....####....S.....#",
      "#....#N.#..........#",
      "#....#..D..........#",
      "#....####..........#",
      "#..................#",
      "#........L.........#",
      "####################",
    ],
    entities: [
      {
        id: "door-back-court",
        type: "door",
        x: 1,
        y: 7,
        label: "Courtyard",
        targetMap: "courtyard",
        targetSpawn: { x: 6, y: 7 },
      },
      {
        id: "npc-elowen-lab",
        type: "npc",
        charId: "elowen",
        x: 13.5,
        y: 4.5,
        color: "#3d7a4f",
        wander: true,
        lines: [
          "The Protease Seal hums north. Walk to it — do not open menus like a quiz app.",
          "After you clear it, the Axon Observatory door wakes.",
        ],
        bond: "elowen",
        xp: 10,
      },
      {
        id: "npc-companion-spot",
        type: "npc",
        charId: "_companion",
        x: 6.5,
        y: 10.5,
        color: "#d4a84b",
        wander: true,
        lines: [
          "I'll scout side halls while you take the seal. Call me when the ward lights.",
          "This wing smells like herbs and ozone. Stay with me — we level by walking too.",
        ],
        bond: null,
        xp: 5,
      },
      {
        id: "seal-protease",
        type: "seal",
        x: 4.5,
        y: 3.5,
        label: "Protease Seal",
        worldId: "wing-asphodel",
        levelId: "d1-main-1",
        glow: "#d4a84b",
      },
      {
        id: "seal-axon",
        type: "seal",
        x: 15,
        y: 9,
        label: "Axon Observatory",
        worldId: "wing-asphodel",
        levelId: "d1-main-2",
        requiresCleared: "d1-main-1",
        glow: "#7ec8e3",
      },
      {
        id: "door-reliquary",
        type: "door",
        x: 8,
        y: 11,
        label: "Acid Reliquary",
        targetMap: "asphodel-deep",
        targetSpawn: { x: 3, y: 5 },
        requiresCleared: "d1-main-2",
        lockedText: "The Reliquary opens after the Observatory seal.",
      },
      {
        id: "chest-asphodel",
        type: "chest",
        x: 10,
        y: 7,
        loot: "asphodel_key",
        xp: 18,
        text: "A brass wing-key. Side corridors will remember you carried it.",
      },
      {
        id: "lore-asphodel",
        type: "lore",
        x: 9,
        y: 14,
        loreId: "asphodel-1",
        xp: 12,
        title: "Asphodel Note",
        text: "Antagonist = key that jams the lock. Picture it while you walk to the seal.",
      },
    ],
  },

  "asphodel-deep": {
    id: "asphodel-deep",
    name: "Acid Reliquary",
    musicCue: "wing-asphodel",
    tile: 40,
    spawn: { x: 3, y: 5 },
    rows: [
      "##############",
      "#............#",
      "#..S....N....#",
      "#............#",
      "#D...........#",
      "#............#",
      "#......C.....#",
      "##############",
    ],
    entities: [
      {
        id: "door-back-asp",
        type: "door",
        x: 1,
        y: 4,
        label: "Asphodel hall",
        targetMap: "asphodel",
        targetSpawn: { x: 8, y: 12 },
      },
      {
        id: "seal-acid",
        type: "seal",
        x: 3.5,
        y: 2.5,
        label: "Acid Reliquary Seal",
        worldId: "wing-asphodel",
        levelId: "d1-main-3",
        glow: "#9fe870",
      },
      {
        id: "npc-bramble-deep",
        type: "npc",
        charId: "bramble",
        x: 9,
        y: 2.5,
        color: "#c4a35a",
        wander: false,
        lines: [
          "Bramble is nervous! pH wards splash. Cast true, then Mercury wing unseals in the courtyard.",
        ],
        bond: "bramble",
        xp: 10,
      },
      {
        id: "chest-deep",
        type: "chest",
        x: 7,
        y: 6,
        loot: "ph_phial",
        xp: 20,
        text: "A phial charm. Remember: pH = −log[H₃O⁺].",
      },
    ],
  },

  mercury: {
    id: "mercury",
    name: "Wing of Mercury",
    musicCue: "wing-mercury",
    tile: 40,
    spawn: { x: 2, y: 7 },
    rows: [
      "##################",
      "#................#",
      "#..S.........N...#",
      "#................#",
      "#................#",
      "#................#",
      "#D..........C....#",
      "#................#",
      "##################",
    ],
    entities: [
      {
        id: "door-merc-back",
        type: "door",
        x: 1,
        y: 6,
        label: "Courtyard",
        targetMap: "courtyard",
        targetSpawn: { x: 14, y: 7 },
      },
      {
        id: "seal-mercury-1",
        type: "seal",
        x: 3.5,
        y: 2.5,
        label: "Alchemy Hall Seal",
        worldId: "wing-mercury",
        levelId: "d2-main-1",
        glow: "#c0c0c0",
      },
      {
        id: "npc-lyra-merc",
        type: "npc",
        charId: "lyra",
        x: 13,
        y: 2.5,
        color: "#7aa0b8",
        wander: true,
        lines: [
          "Day two. HPLC ghosts and kinetics. Walk first — the seal will wait.",
        ],
        bond: "lyra",
        xp: 10,
      },
      {
        id: "chest-merc",
        type: "chest",
        x: 12,
        y: 6,
        loot: "mercury_gear",
        xp: 16,
        text: "A copper cog-charm. Separations favor the patient walker.",
      },
    ],
  },
};
