/**
 * First-person 3D zones for Arcanum (Skyrim-like web spaces).
 * Coordinates in meters. Colliders = axis-aligned boxes {min, max}.
 */
window.EXPLORE3D_WORLDS = {
  courtyard: {
    id: "courtyard",
    name: "Castle Courtyard",
    musicCue: "map",
    spawn: { x: 0, y: 1.65, z: 14 },
    yaw: 0,
    fog: { color: 0x3a4a40, near: 28, far: 95 },
    ambient: 0x8a9a88,
    hemi: { sky: 0xd0d8e0, ground: 0x4a5a48, intensity: 1.35 },
    sun: { color: 0xfff0d0, intensity: 1.95, pos: [18, 28, 10] },
    interactables: [
      {
        id: "npc-elowen",
        type: "npc",
        charId: "elowen",
        position: [-8, 0, -2],
        color: 0x2f5d3a,
        bond: "elowen",
        xp: 8,
        lines: [
          "The courtyard is yours to walk. West arch leads into Asphodel — seals wait inside, not on a board.",
          "Speak to souls. Open chests. When you are ready, challenge the Protease Seal on foot.",
        ],
      },
      {
        id: "npc-cassian",
        type: "npc",
        charId: "cassian",
        position: [8, 0, -2],
        color: 0x8a3420,
        bond: "cassian",
        xp: 6,
        lines: [
          "Finally looking up from parchment. East tower is Mercury — locked until Asphodel yields.",
          "I stashed a wager chest by the fountain. Try not to trip over the cobbles.",
        ],
      },
      {
        id: "npc-bramble",
        type: "npc",
        charId: "bramble",
        position: [0, 0, 2],
        color: 0xc4a35a,
        bond: "bramble",
        xp: 7,
        lines: [
          "Bramble swept these stones! Torches flicker when you near a seal — that is your cue.",
          "Charms in chests help later casts. Walk first. Quiz later.",
        ],
      },
      {
        id: "npc-lyra",
        type: "npc",
        charId: "lyra",
        position: [6, 0, 8],
        color: 0x7aa0b8,
        bond: "lyra",
        xp: 8,
        ghost: true,
        lines: [
          "I remember every footstep that hesitated in this mist.",
          "A lore page rests near the south wall. Memory loves places, not flashcards.",
        ],
      },
      {
        id: "door-asphodel",
        type: "door",
        label: "Wing of Asphodel",
        position: [-10.5, 1.2, -6],
        targetWorld: "asphodel",
        targetSpawn: { x: 0, y: 1.65, z: 8 },
        targetYaw: 0,
      },
      {
        id: "door-mercury",
        type: "door",
        label: "Wing of Mercury",
        position: [10.5, 1.2, -6],
        targetWorld: "mercury",
        targetSpawn: { x: 0, y: 1.65, z: 6 },
        targetYaw: 0,
        requiresWorld: "wing-mercury",
        lockedText: "Sealed. Clear Asphodel's main seals first.",
      },
      {
        id: "chest-rival",
        type: "chest",
        position: [-1.2, 0, 3.5],
        loot: "rival_charm",
        xp: 15,
        text: "Cassian's wager. A Rival Charm — your bond with him deepens.",
      },
      {
        id: "chest-herb",
        type: "chest",
        position: [1.2, 0, 3.5],
        loot: "herb_sachet",
        xp: 12,
        text: "Herb sachet. Bramble would approve — the castle notes your calm.",
      },
      {
        id: "lore-courtyard",
        type: "lore",
        loreId: "courtyard-1",
        position: [0, 0.4, 11],
        xp: 10,
        title: "Courtyard Glyph",
        text: "Walk the world. Level as a scholar. Seals are battles — not the whole map.",
      },
    ],
  },

  asphodel: {
    id: "asphodel",
    name: "Wing of Asphodel",
    musicCue: "wing-asphodel",
    spawn: { x: 0, y: 1.65, z: 8 },
    yaw: 0,
    fog: { color: 0x3a4a40, near: 18, far: 55 },
    ambient: 0x7a8a78,
    hemi: { sky: 0xb0c0b0, ground: 0x3a4a38, intensity: 1.15 },
    sun: { color: 0xffe0b8, intensity: 1.25, pos: [4, 12, 2] },
    interactables: [
      {
        id: "door-back-court",
        type: "door",
        label: "Courtyard",
        position: [0, 1.2, 9.5],
        targetWorld: "courtyard",
        targetSpawn: { x: -9, y: 1.65, z: -4 },
        targetYaw: 0,
      },
      {
        id: "npc-elowen-lab",
        type: "npc",
        charId: "elowen",
        position: [3.5, 0, -2],
        color: 0x2f5d3a,
        bond: "elowen",
        xp: 10,
        lines: [
          "The Protease Seal burns at the far end. Walk to it. Raise no menus like a quiz app.",
          "Clear it, and the Axon Observatory seal wakes deeper in the wing.",
        ],
      },
      {
        id: "npc-companion",
        type: "npc",
        charId: "_companion",
        position: [-3, 0, 2],
        color: 0xd4a84b,
        xp: 5,
        lines: [
          "I'll scout the side halls. Call when the ward lights.",
          "This place smells of herbs and ozone. Stay close — we level by walking too.",
        ],
      },
      {
        id: "seal-protease",
        type: "seal",
        label: "Protease Seal",
        position: [0, 0.05, -7],
        worldId: "wing-asphodel",
        levelId: "d1-main-1",
        glow: 0xd4a84b,
      },
      {
        id: "seal-axon",
        type: "seal",
        label: "Axon Observatory",
        position: [5.5, 0.05, 1],
        worldId: "wing-asphodel",
        levelId: "d1-main-2",
        requiresCleared: "d1-main-1",
        glow: 0x7ec8e3,
      },
      {
        id: "door-reliquary",
        type: "door",
        label: "Acid Reliquary",
        position: [-5.5, 1.2, -1],
        targetWorld: "asphodel-deep",
        targetSpawn: { x: 0, y: 1.65, z: 4 },
        targetYaw: 0,
        requiresCleared: "d1-main-2",
        lockedText: "The Reliquary opens after the Observatory seal.",
      },
      {
        id: "chest-asphodel",
        type: "chest",
        position: [2, 0, 4],
        loot: "asphodel_key",
        xp: 18,
        text: "A brass wing-key. Side corridors will remember you.",
      },
      {
        id: "lore-asphodel",
        type: "lore",
        loreId: "asphodel-1",
        position: [-2, 0.4, 5],
        xp: 12,
        title: "Asphodel Note",
        text: "Antagonist = a key that jams the lock. Picture it while you walk to the seal.",
      },
    ],
  },

  "asphodel-deep": {
    id: "asphodel-deep",
    name: "Acid Reliquary",
    musicCue: "wing-asphodel",
    spawn: { x: 0, y: 1.65, z: 4 },
    yaw: 0,
    fog: { color: 0x2a4030, near: 12, far: 40 },
    ambient: 0x6a8070,
    hemi: { sky: 0xa0c8a8, ground: 0x304038, intensity: 1.1 },
    sun: { color: 0xd8ffc0, intensity: 1.1, pos: [2, 8, 0] },
    interactables: [
      {
        id: "door-back-asp",
        type: "door",
        label: "Asphodel hall",
        position: [0, 1.2, 5.2],
        targetWorld: "asphodel",
        targetSpawn: { x: -5, y: 1.65, z: 0 },
        targetYaw: 0,
      },
      {
        id: "seal-acid",
        type: "seal",
        label: "Acid Reliquary Seal",
        position: [0, 0.05, -3.5],
        worldId: "wing-asphodel",
        levelId: "d1-main-3",
        glow: 0x9fe870,
      },
      {
        id: "npc-bramble-deep",
        type: "npc",
        charId: "bramble",
        position: [2.2, 0, -1],
        color: 0xc4a35a,
        bond: "bramble",
        xp: 10,
        lines: [
          "Bramble is nervous! pH wards splash. Cast true — then Mercury unseals in the courtyard.",
        ],
      },
      {
        id: "chest-deep",
        type: "chest",
        position: [-2, 0, 1],
        loot: "ph_phial",
        xp: 20,
        text: "A phial charm. Remember: pH = −log[H₃O⁺].",
      },
    ],
  },

  mercury: {
    id: "mercury",
    name: "Wing of Mercury",
    musicCue: "wing-mercury",
    spawn: { x: 0, y: 1.65, z: 6 },
    yaw: 0,
    fog: { color: 0x3a4850, near: 16, far: 50 },
    ambient: 0x788898,
    hemi: { sky: 0xc0d0e0, ground: 0x384850, intensity: 1.2 },
    sun: { color: 0xf0f4f8, intensity: 1.4, pos: [6, 14, 2] },
    interactables: [
      {
        id: "door-merc-back",
        type: "door",
        label: "Courtyard",
        position: [0, 1.2, 7.2],
        targetWorld: "courtyard",
        targetSpawn: { x: 9, y: 1.65, z: -4 },
        targetYaw: 0,
      },
      {
        id: "seal-mercury-1",
        type: "seal",
        label: "Alchemy Hall Seal",
        position: [0, 0.05, -5],
        worldId: "wing-mercury",
        levelId: "d2-main-1",
        glow: 0xc0c0c0,
      },
      {
        id: "npc-lyra-merc",
        type: "npc",
        charId: "lyra",
        position: [3, 0, -1],
        color: 0x7aa0b8,
        ghost: true,
        bond: "lyra",
        xp: 10,
        lines: [
          "Day two. Kinetics ghosts in the pipes. Walk the copper hall — the seal waits at the end.",
        ],
      },
      {
        id: "chest-merc",
        type: "chest",
        position: [-2.5, 0, 2],
        loot: "mercury_gear",
        xp: 16,
        text: "A copper cog-charm. Separations favor the patient walker.",
      },
    ],
  },
};
