/**
 * Memory glyphs — visual mnemonics mapped to MCAT topics.
 * Shown during spell casting so concepts stick as images, not quiz text.
 */
window.GLYPHS = {
  enzyme_inhibition: {
    spell: "Ligandum Bindus",
    title: "The Blocking Charm",
    cue: "Antagonist = key that jams the lock (blocks function).",
    svg: "lock",
  },
  stereochemistry: {
    spell: "Speculum Duplex",
    title: "Mirror Cascade",
    cue: "2ⁿ stereoisomers — each chiral center doubles the reflections.",
    svg: "mirrors",
  },
  solubility_ksp: {
    spell: "Precipitus",
    title: "Stonefall Ward",
    cue: "Q > Ksp → stones fall (precipitate forms).",
    svg: "stones",
  },
  peptide_bonds: {
    spell: "Vinculum",
    title: "Bond Sever",
    cue: "HIV protease cuts between Phe…Pro — remember the cut site.",
    svg: "scissors",
  },
  electric_fields: {
    spell: "Vectra Fulmen",
    title: "Fieldline Hex",
    cue: "Field lines leave + and enter − (axon is negative inside).",
    svg: "fields",
  },
  nervous_system: {
    spell: "Myelin Cloak",
    title: "Insulation Cloak",
    cue: "Myelin = rubber coat on a wire — keeps the signal in.",
    svg: "wire",
  },
  membrane_transport: {
    spell: "Canalis Natrium",
    title: "Ion Gate",
    cue: "Channel X carries Na⁺ — small positive ion.",
    svg: "gate",
  },
  waves_circuits: {
    spell: "Tempestas Ohm",
    title: "Pulse Distance",
    cue: "distance ≈ speed × time (0.1 m from 1 ms × 100 m/s).",
    svg: "wave",
  },
  circuits_ohm: {
    spell: "Ohmara",
    title: "Current Law",
    cue: "I = V/R — resistance up, current down.",
    svg: "bolt",
  },
  acids_bases_ph: {
    spell: "Hydronis",
    title: "pH Sigil",
    cue: "pH = −log[H₃O⁺]. 1×10⁻⁵ → pH 5.",
    svg: "phial",
  },
  acids_bases: {
    spell: "Acida Vera",
    title: "Weak Acid Mark",
    cue: "Partial dissociation = weak acid (not fully ionized).",
    svg: "phial",
  },
  periodic_trends: {
    spell: "Elementa",
    title: "Nonmetal Acid",
    cue: "If central atom A is a nonmetal → acidic oxide/acid.",
    svg: "table",
  },
  lipid_metabolism: {
    spell: "Squalenis",
    title: "Steroid Spiral",
    cue: "Squalene → cholesterol → steroid hormones (not sugars).",
    svg: "rings",
  },
  stoichiometry: {
    spell: "Duplicis",
    title: "Ion Double",
    cue: "CaCl₂ → 2 Cl⁻ for every Ca²⁺.",
    svg: "balance",
  },
  carbohydrates: {
    spell: "Speculum Argenti",
    title: "Silver Mirror",
    cue: "No hemiacetal → no aldehyde → sucrose fails Tollens.",
    svg: "mirror",
  },
  amino_acids: {
    spell: "Chargis",
    title: "Residue Charge",
    cue: "Basic residues (Arg, His) carry +; Asp/Glu carry −.",
    svg: "charge",
  },
  amino_acids_charge: {
    spell: "Chargis Major",
    title: "Net Charge Seal",
    cue: "Count ionizable groups at the given pH.",
    svg: "charge",
  },
  separations: {
    spell: "Elutio",
    title: "HPLC Drift",
    cue: "Reverse-phase: polar elutes first from nonpolar column.",
    svg: "column",
  },
  enzyme_kinetics: {
    spell: "Lineweaver",
    title: "Plot Intercept",
    cue: "y-intercept = 1/Vmax. Different Vmax → different intercepts.",
    svg: "plot",
  },
  redox: {
    spell: "Reductio",
    title: "Electron Gift",
    cue: "NADPH donates e⁻ = reducing agent (itself oxidized).",
    svg: "spark",
  },
  fluids_pressure: {
    spell: "Manometra",
    title: "Pressure Tilt",
    cue: "Higher liquid inside → lower gas pressure inside.",
    svg: "tube",
  },
  gas_laws: {
    spell: "Idealis",
    title: "Gas Constant",
    cue: "R = PV/nT — isolate what you need.",
    svg: "balloon",
  },
  experimental_design: {
    spell: "Veritas Lab",
    title: "True Aim",
    cue: "Ask: what variables were they actually measuring?",
    svg: "eye",
  },
  density_units: {
    spell: "Pondus",
    title: "Mass from Density",
    cue: "m = ρV. Keep units consistent.",
    svg: "scale",
  },
  waves_doppler: {
    spell: "Echois",
    title: "Doppler Ear",
    cue: "Need emitted & observed frequencies + speed of sound.",
    svg: "wave",
  },
  intermolecular_forces: {
    spell: "Vincula H",
    title: "H-Bond Lift",
    cue: "HF boils high because of hydrogen bonding.",
    svg: "links",
  },
  atomic_structure: {
    spell: "Orbitalis",
    title: "Cloud Size",
    cue: "n (principal quantum) ≈ radial size of electron cloud.",
    svg: "orbit",
  },
  binding_affinity: {
    spell: "Affinis",
    title: "Binding Shift",
    cue: "Competitors / metals can decrease bound drug.",
    svg: "lock",
  },
  biomolecules: {
    spell: "Similis",
    title: "Like Binds Like",
    cue: "Match polarity + hydrophobicity to the site.",
    svg: "match",
  },
  competitive_binding: {
    spell: "Rivalis",
    title: "Site Contest",
    cue: ">50% displacement by warfarin → Site I.",
    svg: "duel",
  },
  density_thermal: {
    spell: "Densara",
    title: "Hot Wire Mass",
    cue: "ρ = m/V even when temperature changes the story.",
    svg: "scale",
  },
  circuits_resistivity: {
    spell: "Caloris R",
    title: "Heat Resistance",
    cue: "Resistivity rises linearly with T → R rises with T.",
    svg: "bolt",
  },
  thermodynamics: {
    spell: "Calorica",
    title: "Heat Cost",
    cue: "q = mCΔT.",
    svg: "flame",
  },
  organic_labeling: {
    spell: "Carbonis Trace",
    title: "Label Trail",
    cue: "Follow each labeled carbon through the pathway.",
    svg: "path",
  },
  organic_structures: {
    spell: "Forma Vera",
    title: "True Form",
    cue: "Functional groups dictate the correct structure.",
    svg: "hex",
  },
  spectroscopy_ir: {
    spell: "Spectra",
    title: "IR Chorus",
    cue: "OH ~3200–3500; C=O ~1700–1750.",
    svg: "wave",
  },
  optics: {
    spell: "Visio",
    title: "Lens Choice",
    cue: "Myopia needs a diverging lens.",
    svg: "lens",
  },
  phase_changes: {
    spell: "Sublimatio",
    title: "Freeze-Dry",
    cue: "Remove ice by sublimation under reduced pressure.",
    svg: "snow",
  },
  fluids_buoyancy: {
    spell: "Archimedes",
    title: "Buoyant Ratio",
    cue: "Density ∝ Wair / (Wair − Ww).",
    svg: "scale",
  },
  cofactors: {
    spell: "CoA Assemble",
    title: "Cofactor Parts",
    cue: "CoA: β-mercaptoethylamine + pantothenate + ADP pieces.",
    svg: "puzzle",
  },
  default: {
    spell: "Ars Veritas",
    title: "Reasoning Ward",
    cue: "Name the principle, then eliminate.",
    svg: "star",
  },
};

window.glyphFor = function glyphFor(topic) {
  return window.GLYPHS[topic] || window.GLYPHS.default;
};

window.glyphSvg = function glyphSvg(kind) {
  const icons = {
    lock: `<svg viewBox="0 0 64 64" class="glyph-svg"><rect x="18" y="28" width="28" height="24" rx="3" fill="none" stroke="currentColor" stroke-width="3"/><path d="M24 28v-8a8 8 0 0116 0v8" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="40" r="3" fill="currentColor"/></svg>`,
    mirrors: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M20 12l-8 40h16L20 12zm24 0l8 40H36L44 12z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M32 10v44" stroke="currentColor" stroke-width="2" stroke-dasharray="4 3"/></svg>`,
    stones: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M10 44l12-18 10 8 12-14 10 24H10z" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="24" cy="20" r="3" fill="currentColor"/></svg>`,
    scissors: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="18" cy="46" r="8" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="46" cy="46" r="8" fill="none" stroke="currentColor" stroke-width="3"/><path d="M24 40L48 12M40 40L16 12" stroke="currentColor" stroke-width="3"/></svg>`,
    fields: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M12 32c8-16 16-16 24 0s16 16 24 0" fill="none" stroke="currentColor" stroke-width="3"/><path d="M12 44c8-16 16-16 24 0s16 16 24 0" fill="none" stroke="currentColor" stroke-width="2" opacity=".6"/><circle cx="12" cy="32" r="3" fill="currentColor"/><circle cx="52" cy="32" r="3" fill="currentColor"/></svg>`,
    wire: `<svg viewBox="0 0 64 64" class="glyph-svg"><rect x="8" y="28" width="48" height="8" rx="4" fill="none" stroke="currentColor" stroke-width="3"/><rect x="20" y="24" width="10" height="16" rx="2" fill="currentColor" opacity=".35"/><rect x="34" y="24" width="10" height="16" rx="2" fill="currentColor" opacity=".35"/></svg>`,
    gate: `<svg viewBox="0 0 64 64" class="glyph-svg"><rect x="8" y="14" width="48" height="36" rx="4" fill="none" stroke="currentColor" stroke-width="3"/><path d="M8 32h48" stroke="currentColor" stroke-width="2"/><circle cx="32" cy="32" r="6" fill="currentColor"/></svg>`,
    wave: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M4 32c8-14 12-14 20 0s12 14 20 0 12-14 20 0" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    bolt: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M36 6L16 36h14l-4 22 24-34H34l2-18z" fill="currentColor"/></svg>`,
    phial: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M26 8h12v14l10 28a10 10 0 01-10 14H26a10 10 0 01-10-14l10-28V8z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M22 40h20" stroke="currentColor" stroke-width="2"/></svg>`,
    table: `<svg viewBox="0 0 64 64" class="glyph-svg"><rect x="10" y="12" width="44" height="40" fill="none" stroke="currentColor" stroke-width="3"/><path d="M10 28h44M10 40h44M24 12v40M40 12v40" stroke="currentColor" stroke-width="2"/></svg>`,
    rings: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="24" cy="28" r="10" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="36" cy="28" r="10" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="24" cy="40" r="10" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="36" cy="40" r="10" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    balance: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M32 10v40M12 50h40M16 28h32" stroke="currentColor" stroke-width="3"/><circle cx="16" cy="34" r="6" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="48" cy="34" r="6" fill="none" stroke="currentColor" stroke-width="2"/></svg>`,
    mirror: `<svg viewBox="0 0 64 64" class="glyph-svg"><ellipse cx="32" cy="32" rx="14" ry="22" fill="none" stroke="currentColor" stroke-width="3"/><path d="M28 18c6 4 8 12 0 28" fill="none" stroke="currentColor" stroke-width="2"/></svg>`,
    charge: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="22" cy="32" r="12" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="42" cy="32" r="12" fill="none" stroke="currentColor" stroke-width="3"/><path d="M22 26v12M16 32h12M42 26v12" stroke="currentColor" stroke-width="3"/></svg>`,
    column: `<svg viewBox="0 0 64 64" class="glyph-svg"><rect x="26" y="8" width="12" height="48" rx="2" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="20" r="3" fill="currentColor"/><circle cx="32" cy="36" r="3" fill="currentColor" opacity=".7"/><circle cx="32" cy="48" r="3" fill="currentColor" opacity=".4"/></svg>`,
    plot: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M12 12v40h40" fill="none" stroke="currentColor" stroke-width="3"/><path d="M16 44L28 28l10 8 14-22" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    spark: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="20" cy="32" r="8" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="44" cy="32" r="8" fill="currentColor" opacity=".35" stroke="currentColor" stroke-width="3"/><path d="M28 32h8" stroke="currentColor" stroke-width="3"/></svg>`,
    tube: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M20 8v36a12 12 0 0024 0V8" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 34h24" stroke="currentColor" stroke-width="2"/></svg>`,
    balloon: `<svg viewBox="0 0 64 64" class="glyph-svg"><ellipse cx="32" cy="26" rx="16" ry="20" fill="none" stroke="currentColor" stroke-width="3"/><path d="M32 46v10M26 56h12" stroke="currentColor" stroke-width="3"/></svg>`,
    eye: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M8 32c8-14 16-20 24-20s16 6 24 20c-8 14-16 20-24 20S16 46 8 32z" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="32" r="7" fill="currentColor"/></svg>`,
    scale: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M12 44h40M20 44V28h24v16M24 28c0-8 16-8 16 0" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    links: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="22" cy="32" r="10" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="42" cy="32" r="10" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    orbit: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="32" cy="32" r="6" fill="currentColor"/><ellipse cx="32" cy="32" rx="22" ry="10" fill="none" stroke="currentColor" stroke-width="3" transform="rotate(-30 32 32)"/></svg>`,
    match: `<svg viewBox="0 0 64 64" class="glyph-svg"><rect x="12" y="20" width="16" height="24" rx="3" fill="none" stroke="currentColor" stroke-width="3"/><rect x="36" y="20" width="16" height="24" rx="3" fill="none" stroke="currentColor" stroke-width="3"/><path d="M28 32h8" stroke="currentColor" stroke-width="3"/></svg>`,
    duel: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M12 52L28 12M52 52L36 12M20 40h24" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    flame: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M32 8c8 12 16 18 16 30a16 16 0 01-32 0c0-8 6-14 10-20 2 6 6 8 6 14 0 4-2 6-4 8 8-2 12-8 12-16 0-6-4-12-8-16z" fill="currentColor"/></svg>`,
    path: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="12" cy="40" r="4" fill="currentColor"/><circle cx="32" cy="20" r="4" fill="currentColor"/><circle cx="52" cy="36" r="4" fill="currentColor"/><path d="M12 40c8-4 12-16 20-20s12 8 20 16" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    hex: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M32 8l18 10v20L32 56 14 38V18L32 8z" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    lens: `<svg viewBox="0 0 64 64" class="glyph-svg"><circle cx="28" cy="28" r="16" fill="none" stroke="currentColor" stroke-width="3"/><path d="M40 40l14 14" stroke="currentColor" stroke-width="4"/></svg>`,
    snow: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M32 8v48M12 20l40 24M52 20L12 44" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="32" r="4" fill="currentColor"/></svg>`,
    puzzle: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M12 12h18v10a6 6 0 110 12v10H12V12zm22 0h18v40H34V34a6 6 0 100-12V12z" fill="none" stroke="currentColor" stroke-width="3"/></svg>`,
    star: `<svg viewBox="0 0 64 64" class="glyph-svg"><path d="M32 8l6 16h18l-14 12 6 18-16-10-16 10 6-18L8 24h18z" fill="currentColor"/></svg>`,
  };
  return icons[kind] || icons.star;
};
